sudo: required

services: docker

language: python

python: 2.7

env:
  - SWIG_VERSION=3.0.12 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.11 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.10 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.9 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.8 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.7 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.6 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.5 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.4 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.3 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.2 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.1 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.0 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.12 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.11 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.10 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.9 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.8 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.7 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.6 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.5 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.4 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.3 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.2 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.1 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=2.0.0 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.40 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.39 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.38 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.37 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.36 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.35 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.34 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.33 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.32 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.31 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.30 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.29 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.28 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.27 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.25 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.24 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.23 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.22 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.21 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.20 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.19 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.17 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.16 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.15 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.14 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.13 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.12 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.11 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.10 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.9 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.7 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=1.3.6 DISTRIB=ubuntu:xenial
  - SWIG_VERSION=3.0.12 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.11 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.10 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.9 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.8 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.7 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.6 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.5 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.4 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.3 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.2 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.1 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=3.0.0 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.12 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.11 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.10 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.9 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.8 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.7 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.6 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.5 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.4 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.3 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.2 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.1 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=2.0.0 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.40 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.39 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.38 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.37 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.36 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.35 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.34 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.33 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.32 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.31 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.30 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.29 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.28 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.27 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.25 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.24 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.23 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.22 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.21 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.20 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.19 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.17 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.16 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.15 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.14 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.13 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.12 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.11 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.10 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.9 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.7 DISTRIB=ubuntu:trusty
  - SWIG_VERSION=1.3.6 DISTRIB=ubuntu:trusty



before_install:
- docker pull $DISTRIB

install:
- docker run -di --name test_env -v $(pwd):/home/travis/build/vincent-noel/python-libsedml $DISTRIB bash
- docker exec test_env /bin/bash /home/travis/build/vincent-noel/python-libsedml/scripts/install_dep.sh $SWIG_VERSION
- docker exec test_env /bin/bash -c "cd /home/travis/build/vincent-noel/python-libsedml; /usr/bin/python setup.py install"

script:
- docker exec test_env /usr/bin/python -c "import libsedml; a = libsedml.ASTNode(); exit(a.addChild(libsedml.ASTNode()))"